#!/usr/bin/env python3

'''
Script to run authentication user
'''

import os
import sys
# Si falla importar esto --> import proc as proc

try:
    import pexpect
except ImportError:
    print('Required library "pexpect" not exists. Install with pip and try again')
    sys.exit(1)

#Nuestro cliente está en este directorio, así que usamos esta función para meternos en él
os.chdir("./Implementación_Multijugador")

# Define command to request new token
_COMMAND_ = 'python3 get_token.py "%(auth_proxy)s"'

# Message used by authentication client when asking for a password
_PASSWORD_MESSAGE_ = 'Password:'
_TIMEOUT_FOR_MESSAGE_ = 15

# Get required arguments
try:
    user, password, proxy = sys.argv[1:]
except ValueError:
    print('Command arguments: {} <user> <password> <proxy>'.format(
        os.path.basename(sys.argv[0]))
    )
    sys.exit(1)

# Compose command
final_command = _COMMAND_ % {
    'auth_proxy': proxy
}

# Run command
proc = pexpect.spawn(final_command, echo=False)

found = proc.expect(
    #Quitamos el error de pylint porque no podemos evitar que sea tan larga la sentencia
    # pylint: disable=C0301
    ["Introduce tu nombre de usuario: ", pexpect.TIMEOUT, pexpect.EOF], timeout=_TIMEOUT_FOR_MESSAGE_
)
if found == 0:
    # Enter password
    proc.sendline(user)
else:
    # Client execution failed
    print('ERROR: authentication command does not ask for password after {} seconds'.format(
        _TIMEOUT_FOR_MESSAGE_
    ))
    sys.exit(1)

# Wait for client to ask for password
found = proc.expect(
    [_PASSWORD_MESSAGE_, pexpect.TIMEOUT, pexpect.EOF], timeout=_TIMEOUT_FOR_MESSAGE_
)
if found == 0:
    # Enter password
    proc.sendline(password)
    # Wait end
    proc.expect([pexpect.EOF])
else:
    # Client execution failed
    print('ERROR: authentication command does not ask for password after {} seconds'.format(
        _TIMEOUT_FOR_MESSAGE_
    ))
    sys.exit(1)

# Show command output and exit
print(proc.before.decode().strip())
sys.exit(0)
