#!/usr/bin/env python3

'''
Script to run authentication user
'''

import os
import sys
# Si falla importar esto --> import proc as proc

try:
    import pexpect
except ImportError:
    print('Required library "pexpect" not exists. Install with pip and try again')
    sys.exit(1)

#Nuestro cliente está en este directorio, así que usamos esta función para meternos en él
os.chdir("./Implementación_Multijugador")

# Define command to request new token
_COMMAND_ = 'python3 maps_server.py "%(auth_proxy)s"'


# Get required arguments
try:
    proxy = sys.argv[1]
except ValueError:
    print('Command arguments: {} <proxy>'.format(
        os.path.basename(sys.argv[0]))
    )
    sys.exit(1)

# Compose command
final_command = _COMMAND_ % {
    'auth_proxy': proxy
}

# Run command
proc = pexpect.spawn(final_command, echo=False)
print (proc.readline().decode())

try:
    proc.expect([pexpect.EOF], timeout=None)
except KeyboardInterrupt:
    print()
